name=TempSensors_NXP_Arduino
version=1.1.1
author=Tedd OKANO
maintainer=Tedd OKANO
sentence=Class library for NXP temperature sensors
paragraph=LM75B, P3T1035, P3T1084, P3T1085, P3T1755, P3T2030 and PCT2075 are supported
category=Sensors
url=https://github.com/teddokano/TempSensor_Arduino
architectures=*
depends=I2C_device_Arduino (>=0.4.0)
